-- ============================================================
-- DialMyCoffee - Seed: Countries (ISO 3166-1)
-- All ~249 countries grouped by region.
-- ============================================================

INSERT INTO countries (iso2, iso3, name, region) VALUES

-- ============================================================
-- EUROPE
-- ============================================================
('AL', 'ALB', 'Albania', 'Europe'),
('AD', 'AND', 'Andorra', 'Europe'),
('AT', 'AUT', 'Austria', 'Europe'),
('BY', 'BLR', 'Belarus', 'Europe'),
('BE', 'BEL', 'Belgium', 'Europe'),
('BA', 'BIH', 'Bosnia and Herzegovina', 'Europe'),
('BG', 'BGR', 'Bulgaria', 'Europe'),
('HR', 'HRV', 'Croatia', 'Europe'),
('CY', 'CYP', 'Cyprus', 'Europe'),
('CZ', 'CZE', 'Czechia', 'Europe'),
('DK', 'DNK', 'Denmark', 'Europe'),
('EE', 'EST', 'Estonia', 'Europe'),
('FI', 'FIN', 'Finland', 'Europe'),
('FR', 'FRA', 'France', 'Europe'),
('DE', 'DEU', 'Germany', 'Europe'),
('GR', 'GRC', 'Greece', 'Europe'),
('HU', 'HUN', 'Hungary', 'Europe'),
('IS', 'ISL', 'Iceland', 'Europe'),
('IE', 'IRL', 'Ireland', 'Europe'),
('IT', 'ITA', 'Italy', 'Europe'),
('XK', 'XKX', 'Kosovo', 'Europe'),
('LV', 'LVA', 'Latvia', 'Europe'),
('LI', 'LIE', 'Liechtenstein', 'Europe'),
('LT', 'LTU', 'Lithuania', 'Europe'),
('LU', 'LUX', 'Luxembourg', 'Europe'),
('MT', 'MLT', 'Malta', 'Europe'),
('MD', 'MDA', 'Moldova', 'Europe'),
('MC', 'MCO', 'Monaco', 'Europe'),
('ME', 'MNE', 'Montenegro', 'Europe'),
('NL', 'NLD', 'Netherlands', 'Europe'),
('MK', 'MKD', 'North Macedonia', 'Europe'),
('NO', 'NOR', 'Norway', 'Europe'),
('PL', 'POL', 'Poland', 'Europe'),
('PT', 'PRT', 'Portugal', 'Europe'),
('RO', 'ROU', 'Romania', 'Europe'),
('RU', 'RUS', 'Russia', 'Europe'),
('SM', 'SMR', 'San Marino', 'Europe'),
('RS', 'SRB', 'Serbia', 'Europe'),
('SK', 'SVK', 'Slovakia', 'Europe'),
('SI', 'SVN', 'Slovenia', 'Europe'),
('ES', 'ESP', 'Spain', 'Europe'),
('SE', 'SWE', 'Sweden', 'Europe'),
('CH', 'CHE', 'Switzerland', 'Europe'),
('UA', 'UKR', 'Ukraine', 'Europe'),
('GB', 'GBR', 'United Kingdom', 'Europe'),
('VA', 'VAT', 'Vatican City', 'Europe'),

-- ============================================================
-- NORTH AMERICA
-- ============================================================
('AG', 'ATG', 'Antigua and Barbuda', 'North America'),
('BS', 'BHS', 'Bahamas', 'North America'),
('BB', 'BRB', 'Barbados', 'North America'),
('BZ', 'BLZ', 'Belize', 'North America'),
('CA', 'CAN', 'Canada', 'North America'),
('CR', 'CRI', 'Costa Rica', 'North America'),
('CU', 'CUB', 'Cuba', 'North America'),
('DM', 'DMA', 'Dominica', 'North America'),
('DO', 'DOM', 'Dominican Republic', 'North America'),
('SV', 'SLV', 'El Salvador', 'North America'),
('GD', 'GRD', 'Grenada', 'North America'),
('GT', 'GTM', 'Guatemala', 'North America'),
('HT', 'HTI', 'Haiti', 'North America'),
('HN', 'HND', 'Honduras', 'North America'),
('JM', 'JAM', 'Jamaica', 'North America'),
('MX', 'MEX', 'Mexico', 'North America'),
('NI', 'NIC', 'Nicaragua', 'North America'),
('PA', 'PAN', 'Panama', 'North America'),
('KN', 'KNA', 'Saint Kitts and Nevis', 'North America'),
('LC', 'LCA', 'Saint Lucia', 'North America'),
('VC', 'VCT', 'Saint Vincent and the Grenadines', 'North America'),
('TT', 'TTO', 'Trinidad and Tobago', 'North America'),
('US', 'USA', 'United States', 'North America'),

-- ============================================================
-- SOUTH AMERICA
-- ============================================================
('AR', 'ARG', 'Argentina', 'South America'),
('BO', 'BOL', 'Bolivia', 'South America'),
('BR', 'BRA', 'Brazil', 'South America'),
('CL', 'CHL', 'Chile', 'South America'),
('CO', 'COL', 'Colombia', 'South America'),
('EC', 'ECU', 'Ecuador', 'South America'),
('GY', 'GUY', 'Guyana', 'South America'),
('PY', 'PRY', 'Paraguay', 'South America'),
('PE', 'PER', 'Peru', 'South America'),
('SR', 'SUR', 'Suriname', 'South America'),
('UY', 'URY', 'Uruguay', 'South America'),
('VE', 'VEN', 'Venezuela', 'South America'),

-- ============================================================
-- ASIA
-- ============================================================
('AF', 'AFG', 'Afghanistan', 'Asia'),
('AM', 'ARM', 'Armenia', 'Asia'),
('AZ', 'AZE', 'Azerbaijan', 'Asia'),
('BH', 'BHR', 'Bahrain', 'Asia'),
('BD', 'BGD', 'Bangladesh', 'Asia'),
('BT', 'BTN', 'Bhutan', 'Asia'),
('BN', 'BRN', 'Brunei', 'Asia'),
('KH', 'KHM', 'Cambodia', 'Asia'),
('CN', 'CHN', 'China', 'Asia'),
('GE', 'GEO', 'Georgia', 'Asia'),
('IN', 'IND', 'India', 'Asia'),
('ID', 'IDN', 'Indonesia', 'Asia'),
('IR', 'IRN', 'Iran', 'Asia'),
('IQ', 'IRQ', 'Iraq', 'Asia'),
('IL', 'ISR', 'Israel', 'Asia'),
('JP', 'JPN', 'Japan', 'Asia'),
('JO', 'JOR', 'Jordan', 'Asia'),
('KZ', 'KAZ', 'Kazakhstan', 'Asia'),
('KW', 'KWT', 'Kuwait', 'Asia'),
('KG', 'KGZ', 'Kyrgyzstan', 'Asia'),
('LA', 'LAO', 'Laos', 'Asia'),
('LB', 'LBN', 'Lebanon', 'Asia'),
('MY', 'MYS', 'Malaysia', 'Asia'),
('MV', 'MDV', 'Maldives', 'Asia'),
('MN', 'MNG', 'Mongolia', 'Asia'),
('MM', 'MMR', 'Myanmar', 'Asia'),
('NP', 'NPL', 'Nepal', 'Asia'),
('KP', 'PRK', 'North Korea', 'Asia'),
('OM', 'OMN', 'Oman', 'Asia'),
('PK', 'PAK', 'Pakistan', 'Asia'),
('PS', 'PSE', 'Palestine', 'Asia'),
('PH', 'PHL', 'Philippines', 'Asia'),
('QA', 'QAT', 'Qatar', 'Asia'),
('SA', 'SAU', 'Saudi Arabia', 'Asia'),
('SG', 'SGP', 'Singapore', 'Asia'),
('KR', 'KOR', 'South Korea', 'Asia'),
('LK', 'LKA', 'Sri Lanka', 'Asia'),
('SY', 'SYR', 'Syria', 'Asia'),
('TW', 'TWN', 'Taiwan', 'Asia'),
('TJ', 'TJK', 'Tajikistan', 'Asia'),
('TH', 'THA', 'Thailand', 'Asia'),
('TL', 'TLS', 'Timor-Leste', 'Asia'),
('TR', 'TUR', 'Turkey', 'Asia'),
('TM', 'TKM', 'Turkmenistan', 'Asia'),
('AE', 'ARE', 'United Arab Emirates', 'Asia'),
('UZ', 'UZB', 'Uzbekistan', 'Asia'),
('VN', 'VNM', 'Vietnam', 'Asia'),
('YE', 'YEM', 'Yemen', 'Asia'),

-- ============================================================
-- AFRICA
-- ============================================================
('DZ', 'DZA', 'Algeria', 'Africa'),
('AO', 'AGO', 'Angola', 'Africa'),
('BJ', 'BEN', 'Benin', 'Africa'),
('BW', 'BWA', 'Botswana', 'Africa'),
('BF', 'BFA', 'Burkina Faso', 'Africa'),
('BI', 'BDI', 'Burundi', 'Africa'),
('CV', 'CPV', 'Cabo Verde', 'Africa'),
('CM', 'CMR', 'Cameroon', 'Africa'),
('CF', 'CAF', 'Central African Republic', 'Africa'),
('TD', 'TCD', 'Chad', 'Africa'),
('KM', 'COM', 'Comoros', 'Africa'),
('CG', 'COG', 'Congo', 'Africa'),
('CD', 'COD', 'Congo (Democratic Republic)', 'Africa'),
('CI', 'CIV', 'Cote d''Ivoire', 'Africa'),
('DJ', 'DJI', 'Djibouti', 'Africa'),
('EG', 'EGY', 'Egypt', 'Africa'),
('GQ', 'GNQ', 'Equatorial Guinea', 'Africa'),
('ER', 'ERI', 'Eritrea', 'Africa'),
('SZ', 'SWZ', 'Eswatini', 'Africa'),
('ET', 'ETH', 'Ethiopia', 'Africa'),
('GA', 'GAB', 'Gabon', 'Africa'),
('GM', 'GMB', 'Gambia', 'Africa'),
('GH', 'GHA', 'Ghana', 'Africa'),
('GN', 'GIN', 'Guinea', 'Africa'),
('GW', 'GNB', 'Guinea-Bissau', 'Africa'),
('KE', 'KEN', 'Kenya', 'Africa'),
('LS', 'LSO', 'Lesotho', 'Africa'),
('LR', 'LBR', 'Liberia', 'Africa'),
('LY', 'LBY', 'Libya', 'Africa'),
('MG', 'MDG', 'Madagascar', 'Africa'),
('MW', 'MWI', 'Malawi', 'Africa'),
('ML', 'MLI', 'Mali', 'Africa'),
('MR', 'MRT', 'Mauritania', 'Africa'),
('MU', 'MUS', 'Mauritius', 'Africa'),
('MA', 'MAR', 'Morocco', 'Africa'),
('MZ', 'MOZ', 'Mozambique', 'Africa'),
('NA', 'NAM', 'Namibia', 'Africa'),
('NE', 'NER', 'Niger', 'Africa'),
('NG', 'NGA', 'Nigeria', 'Africa'),
('RW', 'RWA', 'Rwanda', 'Africa'),
('ST', 'STP', 'Sao Tome and Principe', 'Africa'),
('SN', 'SEN', 'Senegal', 'Africa'),
('SC', 'SYC', 'Seychelles', 'Africa'),
('SL', 'SLE', 'Sierra Leone', 'Africa'),
('SO', 'SOM', 'Somalia', 'Africa'),
('ZA', 'ZAF', 'South Africa', 'Africa'),
('SS', 'SSD', 'South Sudan', 'Africa'),
('SD', 'SDN', 'Sudan', 'Africa'),
('TZ', 'TZA', 'Tanzania', 'Africa'),
('TG', 'TGO', 'Togo', 'Africa'),
('TN', 'TUN', 'Tunisia', 'Africa'),
('UG', 'UGA', 'Uganda', 'Africa'),
('ZM', 'ZMB', 'Zambia', 'Africa'),
('ZW', 'ZWE', 'Zimbabwe', 'Africa'),

-- ============================================================
-- OCEANIA
-- ============================================================
('AU', 'AUS', 'Australia', 'Oceania'),
('FJ', 'FJI', 'Fiji', 'Oceania'),
('KI', 'KIR', 'Kiribati', 'Oceania'),
('MH', 'MHL', 'Marshall Islands', 'Oceania'),
('FM', 'FSM', 'Micronesia', 'Oceania'),
('NR', 'NRU', 'Nauru', 'Oceania'),
('NZ', 'NZL', 'New Zealand', 'Oceania'),
('PW', 'PLW', 'Palau', 'Oceania'),
('PG', 'PNG', 'Papua New Guinea', 'Oceania'),
('WS', 'WSM', 'Samoa', 'Oceania'),
('SB', 'SLB', 'Solomon Islands', 'Oceania'),
('TO', 'TON', 'Tonga', 'Oceania'),
('TV', 'TUV', 'Tuvalu', 'Oceania'),
('VU', 'VUT', 'Vanuatu', 'Oceania'),

-- ============================================================
-- TERRITORIES & DEPENDENCIES
-- ============================================================
-- Caribbean / North America territories
('AI', 'AIA', 'Anguilla', 'North America'),
('AW', 'ABW', 'Aruba', 'North America'),
('BM', 'BMU', 'Bermuda', 'North America'),
('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'North America'),
('VG', 'VGB', 'British Virgin Islands', 'North America'),
('KY', 'CYM', 'Cayman Islands', 'North America'),
('CW', 'CUW', 'Curacao', 'North America'),
('GL', 'GRL', 'Greenland', 'North America'),
('GP', 'GLP', 'Guadeloupe', 'North America'),
('MQ', 'MTQ', 'Martinique', 'North America'),
('MS', 'MSR', 'Montserrat', 'North America'),
('PR', 'PRI', 'Puerto Rico', 'North America'),
('BL', 'BLM', 'Saint Barthelemy', 'North America'),
('MF', 'MAF', 'Saint Martin (French)', 'North America'),
('PM', 'SPM', 'Saint Pierre and Miquelon', 'North America'),
('SX', 'SXM', 'Sint Maarten (Dutch)', 'North America'),
('TC', 'TCA', 'Turks and Caicos Islands', 'North America'),
('VI', 'VIR', 'U.S. Virgin Islands', 'North America'),

-- South America territories
('FK', 'FLK', 'Falkland Islands', 'South America'),
('GF', 'GUF', 'French Guiana', 'South America'),

-- European territories
('AX', 'ALA', 'Aland Islands', 'Europe'),
('FO', 'FRO', 'Faroe Islands', 'Europe'),
('GI', 'GIB', 'Gibraltar', 'Europe'),
('GG', 'GGY', 'Guernsey', 'Europe'),
('IM', 'IMN', 'Isle of Man', 'Europe'),
('JE', 'JEY', 'Jersey', 'Europe'),
('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Europe'),

-- African territories
('YT', 'MYT', 'Mayotte', 'Africa'),
('RE', 'REU', 'Reunion', 'Africa'),
('SH', 'SHN', 'Saint Helena', 'Africa'),
('EH', 'ESH', 'Western Sahara', 'Africa'),

-- Asian territories
('HK', 'HKG', 'Hong Kong', 'Asia'),
('MO', 'MAC', 'Macao', 'Asia'),

-- Oceania territories
('AS', 'ASM', 'American Samoa', 'Oceania'),
('CK', 'COK', 'Cook Islands', 'Oceania'),
('GU', 'GUM', 'Guam', 'Oceania'),
('NC', 'NCL', 'New Caledonia', 'Oceania'),
('NU', 'NIU', 'Niue', 'Oceania'),
('NF', 'NFK', 'Norfolk Island', 'Oceania'),
('MP', 'MNP', 'Northern Mariana Islands', 'Oceania'),
('PF', 'PYF', 'French Polynesia', 'Oceania'),
('TK', 'TKL', 'Tokelau', 'Oceania'),
('WF', 'WLF', 'Wallis and Futuna', 'Oceania'),

-- Indian Ocean territories
('IO', 'IOT', 'British Indian Ocean Territory', 'Asia'),
('CX', 'CXR', 'Christmas Island', 'Oceania'),
('CC', 'CCK', 'Cocos (Keeling) Islands', 'Oceania'),

-- Antarctic / remote
('AQ', 'ATA', 'Antarctica', 'Antarctica'),
('BV', 'BVT', 'Bouvet Island', 'Antarctica'),
('TF', 'ATF', 'French Southern Territories', 'Antarctica'),
('HM', 'HMD', 'Heard Island and McDonald Islands', 'Antarctica'),
('GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Antarctica'),
('UM', 'UMI', 'United States Minor Outlying Islands', 'Oceania'),
('PN', 'PCN', 'Pitcairn Islands', 'Oceania')

ON CONFLICT (iso2) DO NOTHING;
